### ISSUE TITLE
Micronaut application fails to start when using "Tomcat" HTTP Server

### ISSUE THREAD

**Issue by binoysankar** [micronaut-projects/micronaut-servlet#138]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Create a sample application using the micronaut cli or from https://micronaut.io/launch/ with feature as tomcat-server as below

`mn create-app test-tomcat --features tomcat-server`. Build and run the application.

I am getting the below exception stacktrace.
Note: The issue is only when using "tomcat server". Tried with Jetty and Netty which runs fine. I have raised this issue in Micronaut Gitter forum and seems I am only facing this issue. So I tried running the same in a different machine of mine and getting the same exception.

Exception Stack Trace
==============

> C:\Users\BSANKAR\sample-projects>mn create-app test-tomcat --features tomcat-server
| Application created at C:\Users\BSANKAR\sample-projects\test-tomcat
C:\Users\BSANKAR\sample-projects>cd test-tomcat

C:\Users\BSANKAR\sample-projects\test-tomcat>gradlew run

> Task :run
Jan 07, 2021 7:33:15 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
Jan 07, 2021 7:33:17 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
Jan 07, 2021 7:33:17 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet engine: [Apache Tomcat/9.0.38]
Jan 07, 2021 7:33:17 PM org.apache.catalina.core.ContainerBase startInternal
SEVERE: A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@4d666b41]
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486)
        at io.micronaut.servlet.tomcat.TomcatServer.startServer(TomcatServer.java:60)
        at io.micronaut.servlet.engine.server.AbstractServletServer.start(AbstractServletServer.java:79)
        at io.micronaut.servlet.engine.server.AbstractServletServer.start(AbstractServletServer.java:34)
        at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:70)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:68)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:285)
        at test.tomcat.Application.main(Application.java:8)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@4d666b41]
        at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
        at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4792)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4928)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
        ... 24 more
Caused by: java.lang.IllegalArgumentException: The main resource set specified [C:\Users\BSANKAR\sample-projects\test-tomcat\tomcat.8080\webapps\] is not valid
        at org.apache.catalina.webresources.StandardRoot.createMainResourceSet(StandardRoot.java:751)
        at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:708)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        ... 33 more

Jan 07, 2021 7:33:17 PM org.apache.catalina.core.ContainerBase startInternal
SEVERE: A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: A child container failed during start
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486)
        at io.micronaut.servlet.tomcat.TomcatServer.startServer(TomcatServer.java:60)
        at io.micronaut.servlet.engine.server.AbstractServletServer.start(AbstractServletServer.java:79)
        at io.micronaut.servlet.engine.server.AbstractServletServer.start(AbstractServletServer.java:34)
        at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:70)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:68)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:285)
        at test.tomcat.Application.main(Application.java:8)
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:928)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
        ... 16 more
Caused by: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@4d666b41]
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
        ... 24 more
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@4d666b41]
        at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
        at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4792)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4928)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
        ... 24 more
Caused by: java.lang.IllegalArgumentException: The main resource set specified [C:\Users\BSANKAR\sample-projects\test-tomcat\tomcat.8080\webapps\] is not valid
        at org.apache.catalina.webresources.StandardRoot.createMainResourceSet(StandardRoot.java:751)
        at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:708)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        ... 33 more

19:33:17.884 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error starting HTTP server: A child container failed during start
io.micronaut.http.server.exceptions.HttpServerException: Error starting HTTP server: A child container failed during start
        at io.micronaut.servlet.engine.server.AbstractServletServer.start(AbstractServletServer.java:92)
        at io.micronaut.servlet.engine.server.AbstractServletServer.start(AbstractServletServer.java:34)
        at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:70)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:68)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:285)
        at test.tomcat.Application.main(Application.java:8)
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:928)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486)
        at io.micronaut.servlet.tomcat.TomcatServer.startServer(TomcatServer.java:60)
        at io.micronaut.servlet.engine.server.AbstractServletServer.start(AbstractServletServer.java:79)
        ... 7 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: A child container failed during start
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
        ... 16 common frames omitted
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:928)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
        ... 16 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@4d666b41]
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
        ... 24 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@4d666b41]
        at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
        at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4792)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4928)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
        ... 24 common frames omitted
**Caused by: java.lang.IllegalArgumentException: The main resource set specified [C:\Users\BSANKAR\sample-projects\test-tomcat\tomcat.8080\webapps\] is not valid
        at org.apache.catalina.webresources.StandardRoot.createMainResourceSet(StandardRoot.java:751)
        at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:708)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        ... 33 common frames omitted**

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Binoy\Java_GraalVM\graalvm-ce-java11-20.3.0\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s
3 actionable tasks: 3 executed

### Expected Behaviour

Application should start properly

### Actual Behaviour

Application fails to start

### Environment Information

- **Operating System**: Windows 10 Enterprise
- **Micronaut Version:** 2.2.1
- **JDK Version:** JDK 11 - graalvm-ce-java11-20.3.0

### Example Application

Any application create using the cli or from micronaut with http server as tomcat.

**Comment by binoysankar** [comment]
Update:

I can confirm this is happening only on "Windows OS". Created a sample app in Ubuntu with tomcat-server and the server started properly. Also if I make a docker container and deploy to K8s also it working fine.

Tried to replicated this issue in 3 different Windows machines and all had this startup problem. PFB screenshot

![image](https://user-images.githubusercontent.com/10673905/103982277-3080c380-51a9-11eb-9b56-36aff82862e1.png)

**Comment by binoysankar** [comment]
I am still not able to run tomcat in windows machine with the latest MN 2.5.1 version. Is the support for tomcat is not there for windows?
Just checking the reason for closing the ticket.
