### ISSUE TITLE
Exception when @Get annotation is used in a Groovy application

### ISSUE THREAD

**Issue by sk8geek** [micronaut-projects/micronaut-servlet#2]
It seems that `@Get` causes a `NoSuchMethodError` in the `:compileGroovy` task when trying to start the application. The interesting extract from stacktrace is: 
```
Caused by: java.lang.NoSuchMethodError: io.micronaut.inject.writer.BeanDefinitionVisitor.visitExecutableMethod(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/util/Map;Ljava/lang/String;Ljava/util/Map;Ljava/util/Map;Ljava/util/Map;Ljava/util/Map;Lio/micronaut/core/annotation/AnnotationMetadata;)Lio/micronaut/inject/writer/ExecutableMethodWriter;
    at io.micronaut.ast.groovy.InjectTransform$InjectVisitor.visitExecutableMethod(InjectTransform.groovy:1070)
    at io.micronaut.ast.groovy.InjectTransform$InjectVisitor.visitConstructorOrMethod(InjectTransform.groovy:915)
    at io.micronaut.ast.groovy.InjectTransform$InjectVisitor.visitClass(InjectTransform.groovy:428)
    at io.micronaut.ast.groovy.InjectTransform.visit(InjectTransform.groovy:178)
```
An example application showing this issue is at [https://gitlab.com/sk8geek/mn-servlet-groovy-test](https://gitlab.com/sk8geek/mn-servlet-groovy-test) - HEAD commit is broken, with servlet annotations included, HEAD^1 runs just fine.

**Comment by graemerocher** [comment]
You need to upgrade your Micronaut version to 1.3.3

**Comment by sk8geek** [comment]
Thank you, this fixes the issue.
