### ISSUE TITLE
OAuth2 request body empty

### ISSUE THREAD

**Issue by anatolipr** [micronaut-projects/micronaut-servlet#239]
### Expected Behavior

`io.micronaut.security.oauth2.client.DefaultOpenIdClient#onCallback`
call to `io.micronaut.http.HttpMessage#getBody()` should produce the same result for Netty, Jetty and Tomcat and not error out when using Tomcat/Jetty

### Actual Behaviour

Created a project based on https://guides.micronaut.io/latest/micronaut-oauth2-oidc-google-gradle-java.html 
it worked out of the box with Netty server but throws an exception when I try to use Jetty or Tomcat. Stack trace as follows:

```23:14:38.381 [http-nio-8080-exec-1] ERROR io.micronaut.servlet.http.ServletHttpHandler - Unexpected error occurred: Error decoding request body: Error decoding JSON stream for type [B]: Stream closed
io.micronaut.http.codec.CodecException: Error decoding request body: Error decoding JSON stream for type [B]: Stream closed
	at io.micronaut.servlet.engine.DefaultServletHttpRequest.getBody(DefaultServletHttpRequest.java:193) ~[micronaut-servlet-engine-3.0.0.jar:3.0.0]
	at io.micronaut.http.HttpMessageWrapper.getBody(HttpMessageWrapper.java:70) ~[micronaut-http-3.0.0.jar:3.0.0]
	at io.micronaut.servlet.http.ServletRequestAndBody.getBody(ServletRequestAndBody.java:57) ~[micronaut-servlet-core-3.0.0.jar:3.0.0]
	at io.micronaut.security.oauth2.client.DefaultOpenIdClient.onCallback(DefaultOpenIdClient.java:133) ~[micronaut-security-oauth2-3.0.0.jar:3.0.0]
	at io.micronaut.security.oauth2.routes.DefaultOauthController.callback(DefaultOauthController.java:84) ~[micronaut-security-oauth2-3.0.0.jar:3.0.0]
	at io.micronaut.security.oauth2.routes.$DefaultOauthController$Definition$Exec.dispatch(Unknown Source) ~[micronaut-security-oauth2-3.0.0.jar:3.0.0]
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:338) ~[micronaut-inject-3.0.0.jar:3.0.0]
	at io.micronaut.inject.ExecutionHandle$1.invoke(ExecutionHandle.java:114) ~[micronaut-inject-3.0.0.jar:3.0.0]
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303) ~[micronaut-router-3.0.0.jar:3.0.0]
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111) ~[micronaut-router-3.0.0.jar:3.0.0]
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:128) ~[micronaut-http-3.0.0.jar:3.0.0]
	at io.micronaut.servlet.http.ServletHttpHandler.lambda$buildResponsePublisher$18(ServletHttpHandler.java:560) ~[micronaut-servlet-core-3.0.0.jar:3.0.0]
	at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:94) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8402) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:195) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:282) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:861) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.request(FluxFilterFuseable.java:411) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:139) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2194) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2068) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onSubscribe(MonoPeekTerminal.java:152) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onSubscribe(FluxFilterFuseable.java:305) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4338) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:449) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:219) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4338) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:181) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:102) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:846) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:465) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:292) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:228) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.scheduler.ImmediateScheduler$ImmediateSchedulerWorker.schedule(ImmediateScheduler.java:84) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.FluxSubscribeOn.subscribeOrReturn(FluxSubscribeOn.java:62) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8388) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.Flux.subscribeWith(Flux.java:8575) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8372) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8296) [reactor-core-3.4.8.jar:3.4.8]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8266) [reactor-core-3.4.8.jar:3.4.8]
	at io.micronaut.servlet.http.ServletHttpHandler.subscribeToResponsePublisher(ServletHttpHandler.java:466) [micronaut-servlet-core-3.0.0.jar:3.0.0]
	at io.micronaut.servlet.http.ServletHttpHandler.invokeRouteMatch(ServletHttpHandler.java:401) [micronaut-servlet-core-3.0.0.jar:3.0.0]
	at io.micronaut.servlet.http.ServletHttpHandler.service(ServletHttpHandler.java:227) [micronaut-servlet-core-3.0.0.jar:3.0.0]
	at io.micronaut.servlet.engine.DefaultServletHttpHandler.service(DefaultServletHttpHandler.java:53) [micronaut-servlet-engine-3.0.0.jar:3.0.0]
	at io.micronaut.servlet.engine.DefaultMicronautServlet.service(DefaultMicronautServlet.java:66) [micronaut-servlet-engine-3.0.0.jar:3.0.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) [javax.servlet-api-4.0.1.jar:4.0.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.38.jar:9.0.38]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.38.jar:9.0.38]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.micronaut.http.codec.CodecException: Error decoding JSON stream for type [B]: Stream closed
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.decode(JacksonMediaTypeCodec.java:144) ~[micronaut-runtime-3.0.0.jar:3.0.0]
	at io.micronaut.servlet.engine.DefaultServletHttpRequest.getBody(DefaultServletHttpRequest.java:188) ~[micronaut-servlet-engine-3.0.0.jar:3.0.0]
	... 80 more
Caused by: java.io.IOException: Stream closed
	at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:359) ~[tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:132) ~[tomcat-embed-core-9.0.38.jar:9.0.38]
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.ensureLoaded(ByteSourceJsonBootstrapper.java:539) ~[jackson-core-2.12.4.jar:2.12.4]
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.detectEncoding(ByteSourceJsonBootstrapper.java:133) ~[jackson-core-2.12.4.jar:2.12.4]
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructParser(ByteSourceJsonBootstrapper.java:256) ~[jackson-core-2.12.4.jar:2.12.4]
	at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1656) ~[jackson-core-2.12.4.jar:2.12.4]
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1085) ~[jackson-core-2.12.4.jar:2.12.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3601) ~[jackson-databind-2.12.4.jar:2.12.4]
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.decode(JacksonMediaTypeCodec.java:139) ~[micronaut-runtime-3.0.0.jar:3.0.0]
	at io.micronaut.servlet.engine.DefaultServletHttpRequest.getBody(DefaultServletHttpRequest.java:188) ~[micronaut-servlet-engine-3.0.0.jar:3.0.0]
	... 80 more```

### Steps To Reproduce

1. download example project ZIP from https://guides.micronaut.io/latest/micronaut-oauth2-oidc-google-gradle-java.html 
2. edit application.yaml and specify a valid `client-id`and `client-secret` values as per your Google API credential settings 
3. edit build.gradle and change `micronaut` section by defining either tomcat or jetty as a `runtime` value. Eg. ```micronaut {
    runtime("tomcat")
    testRuntime("junit5")
    processing {
        incremental(false)
        annotations("com.example.*")
    }
}```

Run the app and authenticate with google. Upon successful callback request back to `/oauth/callback/google?...` you'd be faced with the above exception in the logs and respectively an error 500 response.

### Environment Information

- MacOS
- Java 8

### Example Application

_No response_

### Version

3.0.0

**Comment by anatolipr** [comment]
Similar to the above when using Tomcat or Jetty with https://guides.micronaut.io/latest/micronaut-security-jwt-cookie-gradle-java.html example after POST to /login the response sent is 401

**Comment by graemerocher** [comment]
fixed in master
