### ISSUE TITLE
will not work on Glassfish / Payara server

### ISSUE THREAD

**Issue by kbachl** [micronaut-projects/micronaut-servlet#7]
create a hello world app like (micronaut version 1.3.5):
mn 
create-app hello-world --lang=groovy
create-controller hello

add to build.gradle:
developmentOnly("io.micronaut.servlet:micronaut-http-server-tomcat:1.0.0.M3")
    implementation("io.micronaut.servlet:micronaut-servlet-engine:1.0.0.M3")

plugins: id "war"

build war, deploy to payara 5.201 (current version):

exception at deploy:

[2020-05-10T12:07:44.589+0200] [Payara 5.201] [SCHWERWIEGEND] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=140 _ThreadName=admin-thread-pool::admin-listener(2)] [timeMillis: 1589105264589] [levelValue: 1000] [[
  Exception during lifecycle processing
java.lang.IllegalStateException: The return type of the lifecycle method [stop] must be void. Related annotation information: annotation [@javax.annotation.PreDestroy()] on annotated element [public io.micronaut.http.client.HttpClient io.micronaut.http.client.DefaultHttpClient.stop()] of type [METHOD]
	at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:538)
	at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:458)
....
Caused by: The return type of the lifecycle method [stop] must be void. Related annotation information: annotation [@javax.annotation.PreDestroy()] on annotated element [public io.micronaut.http.client.HttpClient io.micronaut.http.client.DefaultHttpClient.stop()] of type [METHOD]
	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:401)
	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:409)
	at org.glassfish.apf.impl.AnnotationProcessorImpl.processAnnotations(AnnotationProcessorImpl.java:319)
	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:246)
	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:153)
	at com.sun.enterprise.deployment.archivist.Archivist.processAnnotations(Archivist.java:651)
	at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:474)
	... 67 more
Caused by: java.lang.IllegalArgumentException: The return type of the lifecycle method [stop] must be void
	at com.sun.enterprise.deployment.annotation.handlers.AbstractResourceHandler.validateAnnotatedLifecycleMethod(AbstractResourceHandler.java:197)
	at com.sun.enterprise.deployment.annotation.handlers.PreDestroyHandler.processAnnotation(PreDestroyHandler.java:69)
	at com.sun.enterprise.deployment.annotation.handlers.AbstractResourceHandler.processAnnotation(AbstractResourceHandler.java:147)
	at com.sun.enterprise.deployment.annotation.factory.SJSASFactory$LazyAnnotationHandler.processAnnotation(SJSASFactory.java:170)
	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:380)
	... 73 more
]]

[2020-05-10T12:07:44.620+0200] [Payara 5.201] [SCHWERWIEGEND] [] [javax.enterprise.system.core] [tid: _ThreadID=140 _ThreadName=admin-thread-pool::admin-listener(2)] [timeMillis: 1589105264620] [levelValue: 1000] [[
  Exception while deploying the app [hello-world2-0.1] : The return type of the lifecycle method [stop] must be void. Related annotation information: annotation [@javax.annotation.PreDestroy()] on annotated element [public io.micronaut.http.client.HttpClient io.micronaut.http.client.DefaultHttpClient.stop()] of type [METHOD]
The return type of the lifecycle method [stop] must be void. Related annotation information: annotation [@javax.annotation.PreDestroy()] on annotated element [public io.micronaut.http.client.HttpClient io.micronaut.http.client.DefaultHttpClient.stop()] of type [METHOD]
	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:401)
	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:409)

**Comment by graemerocher** [comment]
You need to disable CDI scanning. See https://stackoverflow.com/questions/43608988/guice-deployment-exception/43717446#43717446

**Comment by kbachl** [comment]
It should work by disabling "Implicit CDI" in the server console or by having e.g:
<glassfish-application>
    <enable-implicit-cdi>false</enable-implicit-cdi>
</glassfish-application>
in the glassfish-application.xml

Yet, the error still exists even after doing that

**Comment by graemerocher** [comment]
Seems like a bug in Glassfish in that case and I would report an issue there

**Comment by kbachl** [comment]
likely, will do that;
Follow up: 
even a beans.xml containing that will not work:
```
<?xml version="1.0" encoding="UTF-8" ?>
<beans bean-discovery-mode="none">
</beans>
```

**Comment by kbachl** [comment]
@graemerocher can you please have a look at the response from the payara team as they say the problem lies within micronaut putting things into the war that shouldn't be there?
https://github.com/payara/Payara/issues/4661
