### ISSUE TITLE
SSL certificate used for tests has expired

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-servlet#75]
The three "SslSpec" tests have started to fail on master branch but they all passed 3 days ago: https://github.com/micronaut-projects/micronaut-servlet/actions/runs/283776958

It turns out that the `KeyStore.p12` certificate used for the tests has expired:

![image](https://user-images.githubusercontent.com/559192/95073115-983bf400-070c-11eb-92e3-bf6bd2903d23.png)

**Comment by graemerocher** [comment]
@jameskleeh did you generate this certificate?

**Comment by ilopmar** [comment]
I'm trying to create a new one...

**Comment by ilopmar** [comment]
@jameskleeh It seems I'm unable to create a valid CA and then a certificate that currently works. I've managed to create one but only worked for Jetty. Do you have instructions for how to do this?

**Comment by jameskleeh** [comment]
@graemerocher As far as I can tell https://github.com/micronaut-projects/micronaut-servlet/commit/fafc1b78d7cc359db27169cca5a88220f42b459a#diff-5a2c19a537c599e14334f7d781618c65 you added the certificates. If you grabbed them from somewhere else in core then it's possible I created them.

**Comment by graemerocher** [comment]
it is likely the tests for core will fail soon too :)

**Comment by ilopmar** [comment]
Hahaha. In my attempts I'm using `-days 9999`

**Comment by ilopmar** [comment]
Nothing that I'm trying actually works. I'm probably doing something wrong or missing some step that I can't figure out.

I've followed two approaches, one using a CA that signs the server certificate and another one with only a server certificate without the CA. None of them works :pensive: 

Maybe anyone can give it another try...


## Using a CA

### Create CA Certificate

```
$ openssl genrsa -des3 -out rootCA.key 4096
$ openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 9999 -out rootCA.crt
```

### Server certificate request

```
$ openssl genrsa -out server.key 2048
$ openssl req -new -key server.key -out server.csr
```

### Create server certificate and sign request

```
$ openssl x509 -req -in server.csr -CA rootCA.crt -CAkey rootCA.key -CAcreateserial -out server.crt -days 9999 -sha256
```

### Convert server.crt to server.p12

```
$ openssl pkcs12 -export -in server.crt -inkey server.key -out server.p12                                                 
# Mandatory to put some password or the next conversion will fail with NPE. Maybe it's an issue in my machine of JDK version 
```

### Convert server.p12 to server.jks

```
$ keytool -importkeystore -destkeystore server.jks -srckeystore server.p12 -srcstoretype pkcs12                  
```

### Display content of JKS

```
$ keytool -v -list -keystore server.jks
```

### Test `JettySslSpec`

Then using this the generated `server.p12` and `server.jks` in the `JettySslSpec` test fails with:

```
javax.net.ssl.SSLException: Received fatal alert: bad_certificate
java.lang.RuntimeException: javax.net.ssl.SSLException: Received fatal alert: bad_certificate
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.subscribers.BlockingBaseSubscriber.blockingGet(BlockingBaseSubscriber.java:78)
	at io.reactivex.Flowable.blockingFirst(Flowable.java:5699)
	at io.micronaut.servlet.jetty.JettySslSpec.test certificate extraction(JettySslSpec.groovy:26)
Caused by: javax.net.ssl.SSLException: Received fatal alert: bad_certificate
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:214)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1667)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1635)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1801)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1090)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:913)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:783)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:626)
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:281)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1340)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

18:01:39.274 [Test worker] INFO  o.e.jetty.server.AbstractConnector - Stopped ServerConnector@4cea2a6a{SSL, (ssl, http/1.1)}{0.0.0.0:23465}
18:01:39.275 [Test worker] INFO  o.e.jetty.server.AbstractConnector - Stopped ServerConnector@7d3d377c{HTTP/1.1, (http/1.1)}{localhost:62827}
18:01:39.305 [Test worker] INFO  o.e.j.server.handler.ContextHandler - Stopped i.m.s.j.@29523bdc{/,null,STOPPED}
```

---

## Not using a CA

### Create server key

```
$ openssl genrsa -des3 -out keypair.key 2048
$ openssl rsa -in keypair.key -out server.key
$ rm keypair.key
```

### Server CSR and certificate

```
$ openssl req -new -key server.key -out server.csr
$ openssl x509 -req -days 9999 -in server.csr -signkey server.key -out server.crt
```

### Create P12, JKS and display

As before

```
$ openssl pkcs12 -export -in server.crt -inkey server.key -out server.p12                                                 
# Mandatory to put some password or the next conversion will fail with NPE. Maybe it's an issue in my machine of JDK version 

$ keytool -importkeystore -destkeystore server.jks -srckeystore server.p12 -srcstoretype pkcs12

$ keytool -v -list -keystore server.jks
```

### Tests

With these new files `server.p12` and `server.jks`, `JettySslSpec` and `UndertowSslSpec` tests pass and `TomcatSslSpec` fails with the following error which I'm stuck and don't know what else to try:

```
org.apache.catalina.LifecycleException: Protocol handler initialization failed
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:1042)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:533)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:1057)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:173)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486)
	at io.micronaut.servlet.tomcat.TomcatServer.startServer(TomcatServer.java:60)
	at io.micronaut.servlet.engine.server.AbstractServletServer.start(AbstractServletServer.java:77)
	at io.micronaut.servlet.engine.server.AbstractServletServer.start(AbstractServletServer.java:32)
	at io.micronaut.test.extensions.AbstractMicronautExtension.beforeClass(AbstractMicronautExtension.java:230)
	at io.micronaut.test.extensions.spock.MicronautSpockExtension.lambda$visitSpecAnnotation$3(MicronautSpockExtension.java:97)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:101)
	at org.spockframework.runtime.PlatformSpecRunner.invoke(PlatformSpecRunner.java:396)
	at org.spockframework.runtime.PlatformSpecRunner.runSetupSpec(PlatformSpecRunner.java:129)
	at org.spockframework.runtime.PlatformSpecRunner.runSetupSpec(PlatformSpecRunner.java:124)
	at org.spockframework.runtime.SpecNode.before(SpecNode.java:46)
	at org.spockframework.runtime.SpecNode.before(SpecNode.java:8)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.spockframework.runtime.SpockNode.sneakyInvoke(SpockNode.java:24)
	at org.spockframework.runtime.SpecNode.lambda$around$0(SpecNode.java:61)
	at org.spockframework.runtime.PlatformSpecRunner.lambda$createMethodInfoForDoRunSpec$0(PlatformSpecRunner.java:62)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:136)
	at org.spockframework.runtime.PlatformSpecRunner.invokeRaw(PlatformSpecRunner.java:405)
	at org.spockframework.runtime.PlatformSpecRunner.invoke(PlatformSpecRunner.java:388)
	at org.spockframework.runtime.PlatformSpecRunner.runSpec(PlatformSpecRunner.java:56)
	at org.spockframework.runtime.SpecNode.around(SpecNode.java:61)
	at org.spockframework.runtime.SpecNode.around(SpecNode.java:8)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:87)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:53)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:66)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:87)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:66)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: the trustAnchors parameter must be non-empty
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:99)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:71)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:216)
	at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1141)
	at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1154)
	at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:581)
	at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:75)
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:1039)
	... 83 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:157)
	at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:130)
	at org.apache.tomcat.util.net.SSLUtilBase.getParameters(SSLUtilBase.java:501)
	at org.apache.tomcat.util.net.SSLUtilBase.getTrustManagers(SSLUtilBase.java:432)
	at org.apache.tomcat.util.net.SSLUtilBase.createSSLContext(SSLUtilBase.java:246)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:97)
	... 90 more
```

**Comment by ilopmar** [comment]
For future reference, @jameskleeh figured this out without using a CA:

```
openssl genrsa -des3 -out server.key 2048
openssl req -new -key server.key -out server.csr
openssl x509 -req -days 9999 -in server.csr -signkey server.key -out server.crt
cat server.key > server.pem
cat server.crt >> server.pem
openssl pkcs12 -export -in server.pem -out KeyStore.pkcs12
keytool -import -file server.crt -alias ca -keystore TrustStore.jks
```
